from __future__ import annotations
from src.contracts.agent_result import QualityStatus
REFERENCE={'EMPTY_REPRESENTATIVE_SOURCE','INVALID_REPRESENTATIVE_SOURCE','TITLE_MISMATCH','INVALID_STRUCTURE_SOURCE','INVALID_GAP_SOURCE','INVALID_COMPARATIVE_SOURCE'}
EVIDENCE={'MISSING_THEME_EVIDENCE','UNSUPPORTED_THEME','MISSING_GAP_EVIDENCE','UNSUPPORTED_RESEARCH_GAP','MISSING_COMPARATIVE_EVIDENCE','INVALID_COMPARATIVE_DIMENSION','UNASSIGNED_PAPERS','PAPER_COVERAGE_BELOW_TARGET'}
SCHEMA={'INVALID_LLM_OUTPUT','INVALID_THEMATIC_SCHEMA','EMPTY_THEMATIC_OUTPUT','INVALID_THEME_RECORD','INVALID_GAP_RECORD','INVALID_STRUCTURE_RECORD','INVALID_COMPARATIVE_DIMENSION_RECORD','STRUCTURE_TOO_SHORT','STRUCTURE_TOO_LONG'}
def classify_quality(codes,attempt,manual_allowed=True):
    c=set(codes)
    if not c:return QualityStatus.APPROVED,'ADVANCE'
    if attempt>=2:
        if manual_allowed and not (c&REFERENCE): return QualityStatus.APPROVED_PENDING_MANUAL_REVIEW,'HALT_STAGE'
        return QualityStatus.REJECTED,'STOP_PIPELINE'
    if c&EVIDENCE:return QualityStatus.NEEDS_MORE_EVIDENCE,'RETRY'
    return QualityStatus.NEEDS_REVISION,'RETRY'
